/**
 * Per-MCP-session attachment state for the HTTP MCP endpoint.
 *
 * Each MCP client connection (keyed by MCP session ID from
 * StreamableHTTP transport) maintains its own attachment — which project
 * and optionally which task within that project the session is "looking at".
 *
 * Unscoped tools (list_projects, attach_to, get_attachment) ignore this state.
 * Scoped tools (get_tree, get_task, get_logs, read_file, list_files, search)
 * read attachedProject + attachedTask out of the session state and execute
 * in that context.
 *
 * WHY: External Claude Code can query Matrix state from its own CC session
 * without context-switching to Matrix's web UI. Dynamic attachment lets one
 * MCP connection serve multiple projects/tasks over its lifetime without
 * re-establishing the transport.
 */

export interface McpAttachment {
	projectId: string;
	/** Optional — if undefined, session is attached at project level only. */
	taskId?: string;
}

export interface McpSessionState {
	/** The MCP session ID from StreamableHTTP transport. */
	mcpSessionId: string;
	/** Current attachment. Undefined until attach_to() is called. */
	attachment?: McpAttachment;
	/** When this session was created (unix ms). */
	createdAt: number;
}

/**
 * In-memory store of MCP session states.
 * Keyed by MCP session ID (generated by transport's sessionIdGenerator).
 */
export class McpSessionStore {
	private sessions = new Map<string, McpSessionState>();

	/** Create a new session state. Returns the state. */
	create(mcpSessionId: string): McpSessionState {
		const state: McpSessionState = {
			mcpSessionId,
			createdAt: Date.now(),
		};
		this.sessions.set(mcpSessionId, state);
		return state;
	}

	/** Get an existing session state. */
	get(mcpSessionId: string): McpSessionState | undefined {
		return this.sessions.get(mcpSessionId);
	}

	/** Remove a session (on transport close). */
	delete(mcpSessionId: string): boolean {
		return this.sessions.delete(mcpSessionId);
	}

	/** Update attachment. Throws if session doesn't exist. */
	attach(mcpSessionId: string, attachment: McpAttachment): void {
		const state = this.sessions.get(mcpSessionId);
		if (!state) {
			throw new Error(`MCP session not found: ${mcpSessionId}`);
		}
		state.attachment = attachment;
	}

	/** Clear attachment. No-op if session doesn't exist. */
	detach(mcpSessionId: string): void {
		const state = this.sessions.get(mcpSessionId);
		if (state) state.attachment = undefined;
	}

	/** Get the count of active sessions. */
	size(): number {
		return this.sessions.size;
	}

	/** List all session IDs. */
	list(): string[] {
		return Array.from(this.sessions.keys());
	}
}
